# Generated by Django 5.1.1 on 2024-09-11 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expance_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Other', 'Other')])),
            ],
            options={
                'verbose_name': 'Transaction_Table',
                'db_table': 'Transaction_Table',
                'ordering': ('-amount',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_gt_0')],
            },
        ),
    ]
