# Generated by Django 5.1.1 on 2024-09-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='amount_gt_0',
        ),
    ]
